---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
spec:
  tower_ingress_type: Ingress
  tower_admin_password_secret: 1233ss77qqWW
  tower_admin_user: admin
  tower_admin_email: test@example.com
