- hosts: naszaaplikacja

  become: true

  #zmienne przydatne do parametryzacji wgrania, oraz szablonowania konfiguracji
  vars:
    katalog_aplikacji: /var/www/szkolenie
    log_dir: /var/www/szkolenie/logs/
    port: 5081

  pre_tasks: []

  tasks:
    - name: 'zainstaluj aplikacje apache2 i libapache2-mod-wsgi przekazując listę'

    - name: 'zainstaluj aplikacje apache2 i pozostale pakiety przy pomocy with_items'

    - name: 'wgraj definicje virtualhost naszaaplikacja.apache.conf jako template'

    - name: 'wlacz virtualhost'

    - name: 'klonuj repozytorium aplikacji'

    - name: 'zainicjalizuj virtualenv i zainstaluj zaleznosci' 

    - name: 'Wgraj sparametryzowany naszaaplikacja.wsgi (jako template)'

    - name: 'utworz katalog na logi'

    - name: 'restart apache'
