#ami: ami-f1d7c395
ami: ami-061a2d878e5754b62
region: eu-west-2
subnet: subnet-b516cbce
sg: szkolenie3-security-group
#key: szkolenie_05_london
key: szkolenie_05_london_sodo
ansible_ssh_private_key_file: '~/.ssh/szkolenie_05_london_sodo.pem'
location: london
assign_public_ip: True
#ec2_url: "https://ec2.eu-west-2.amazonaws.com"
