all:
  hosts:
    kubapseudohost:
  vars:
    system_env: szkolenie
    location: london_akademiaansible
  children:
    mylocalhost:
      hosts:
        localhost: 
          ansible_connection: local
          ansible_python_interpreter: "/usr/bin/env python"
    mgmt:
      hosts:
        mgmt2.muszynski.pro:
          ansible_ssh_private_key_file: ~/.ssh/szkolenie_05_london.pem
          ciekawa_zmienna: ddddddd
          jeszcze_inna: 1234
    jenkins:
      hosts:
        35.177.203.22:
    apache:
      hosts:
        13.40.116.174:
        ec2-3-8-95-149.eu-west-2.compute.amazonaws.com:
      vars:
    backend:
      hosts:
        18.170.71.6:
    prod:
      children:
        apache:
        backend:
    wordpress:
      hosts:
        3.10.235.80:
    loadbalancer:
      hosts:
        3.10.235.89:
    mysql:
      hosts:
        3.10.235.89:
    zabbix_agent:
      hosts:
        3.10.235.89:
    naszaaplikacja:
      hosts:
        3.10.235.89:
    naszaaplikacja:
      hosts:
        3.10.235.89:
    naszaaplikacja_mysql:
      hosts:
        3.10.235.89:
    naszaaplikacja_loadbalancer:
      hosts:
        3.10.235.89:
