# Example using filters, ignoring permission errors, and specifying the hostname precedence
plugin: aws_ec2
# The values for profile, access key, secret key and token can be hardcoded like:
#boto_profile: aws_profile
# or you could use Jinja as:
# boto_profile: "{{ lookup('env', 'AWS_PROFILE') | default('aws_profile', true) }}"
# Populate inventory with instances in these regions
#regions:
#  - us-east-1
#  - us-east-2
#filters:
#  # All instances with their `Environment` tag set to `dev`
#  tag:Environment: dev
#  # All dev and QA hosts
#  tag:Environment:
#    - dev
#    - qa
#  instance.group-id: sg-xxxxxxxx
# Ignores 403 errors rather than failing
strict_permissions: False
# Note: I(hostnames) sets the inventory_hostname. To modify ansible_host without modifying
# inventory_hostname use compose (see example below).
keyed_groups:
  - prefix: tag
    key: tags
