# roles/cat_site/tasks/main.yml
---
- name: Create the HTML file
  template:
    src: index.html.j2
    dest: /var/www/html/index.html

- name: Stop the web server
  #command: python -m http.server 8080
  shell: kill -9 $(pgrep 'python3 -m http.server' -f)
  become: yes
  ignore_errors: true

- name: Start the web server
  #command: python -m http.server 8080
  shell: python3 -m http.server 8080 -d /var/www/html/ >> /tmp/log.txt 2>&1 &
  become: yes

