apache_conf_path: /etc/apache2
apache_listen_ip: 0.0.0.0
apache_listen_port: 80

vhosts_set:
  - servername: wp.twojadomena.pl
    serveralias: [wp.innadomena.net]
    staticpart: '#RequestHeader set Host wp.twojadomena.pl'
    proxy_set:
      - uri_match: '/'
        dest: "http://{{ hostvars[groups['wordpress'][0]].ansible_default_ipv4.address }}/wordpress/"
        #dest: "http://{{ hostvars[groups['wordpress'][0]].ansible_default_ipv4.address }}/"

vhosts_set_balancer: []
#  - servername: wp.twojadomena.pl
#    serveralias: [wp.innadomena.net]
#    staticpart: '#RequestHeader set Host wp.twojadomena.pl'
#    proxy_set:
#      - uri_match: '/'
#        dest: "wordpress/"
#    nazwa_balancera: klaster_wordpress
#    hosty_wp: "{{ groups['wordpress'] }}"
