---
galaxy_info:
  author: uczestnik_szkolenia
  description: Prosty serwer www z parametryzowana strona (material szkoleniowy)
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble

dependencies: []
