---
galaxy_info:
  author: szkolenie
  description: Rola instalujaca i konfigurujaca Apache webserver
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - "22.04"
        - "24.04"

dependencies: []
