version: '2'

services:
  ansible-master:
    image: ubuntu
    build: 
      context: ./
    container_name: ansible-master
    environment:
      example: aaa
    volumes: []
    #  - dir:/var/dir
    #restart: always
    ports:
      - "8000:80"

volumes:
  dir:
