---
- name: przyklad szablonow w playbook
  hosts: localhost
  gather_facts: no
  tasks:
    - name: wypisz na ekran
      copy:
        content: |
          OK
        dest: /tmp/flaga_instalacji


    - name: echo z szablonu i filtra jinja2
      shell: "echo {{ [1, 2, 5] | max }}" 
      
     

