# repo: my-eda-repo/rulebooks/webhook_restart.yml
- name: Webhook -> run AWX JT
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Restart Apache via AWX
      condition: >
        event.payload is defined and
        event.payload.service == "apache2" and
        event.payload.state in ["down", "critical"]
      action:
        run_job_template:
          name: "Restart Apache JT"        # nazwa JT w AWX
          organization: "Default"
          job_args:
            limit: "{{ event.payload.limit | default('') }}"
            extra_vars:
              eda_payload: "{{ event.payload }}"

