---
#Uruchomienie:
#~/szkolenie$ ansible-playbook playbooks/configure_apache.yml
#
- hosts: apache

  vars:
      vars_files_var: ["vars/szkolenie.yml", "vars/szkolenie_vault.yml"]

  pre_tasks:
      - include_vars: "{{ item }}"
        with_items: "{{ vars_files_var }}"

  tasks:
  - name: update cache 
    apt: update_cache=yes cache_valid_time=7200
    changed_when: False
    become: True

  - name: install packages
    apt: name={{ item }}
    with_items:
    - apache2
    - htop
    - dstat
    become: True

  - name: Wait for instances to listen on port 80
    wait_for: state=started host=localhost port=80 timeout=15 delay=5

  - name: create file directory 
    file: 
      path: "~/szkolenie_playbooks_{{ nazwa_uzytkownika }}"
      state: directory
      mode: 0775
    vars:
      nazwa_uzytkownika: szkolenie01

  - name: create file directory with lookup
    file: 
      path: "~/szkolenie_playbooks_{{ nazwa_uzytkownika }}"
      state: directory
      mode: 0775
    vars:
      nazwa_uzytkownika: "{{ lookup('pipe', 'whoami') }}"
