---
- hosts: all

  name: first playbook

  vars:
    zmiennaA: 1234

  vars_files:
    - "vars/{{ our_env | default(system_env) }}.yml"

  tasks:
    - ping:
      ignore_errors: True

    - ping:
      name: optional name parameter
      register: saved_output
      faled_when: False
      changed_when: False

    - debug: var=ansible_facts

  #roles:
  #  - sys_debug

  handlers:
    - name: restart apache
      ping:



  #this is a commoent
  gather_facts: smart
  become: True
  
  pre_tasks: []
  post_tasks: []


- hosts: all
  name: Second playbook
