- hosts: localhost
  vars:
    k8s_namespace: przyklad

  tasks:
    - name: Wygeneruj szablon
      template: 
        #src: home.tmpl
        src: home.tmpl_j2
        dest: ~/wynik.html

#https://github.com/heptiolabs/gangway/blob/master/templates/home.tmpl       
