---
    - name: debug input group
      debug:
        msg: "{{ outer_group_item }}"

    - name: debug sequence number
      debug:
        msg: "{{ outer_group_item }}"

    #for all hosts in group, add to correct run_X group
    - name: add_host to run_X group
      add_host:
        name: "{{ outer_group_item.value[item|int] }}"
        groups: "run_{{ item }}"
      loop: "{{ group_elements_count_max_sequence }}"
      when:
        - 'outer_group_item.value[item|int] | default(False)'
#
#    - name: list groups
#      debug: 
#        msg: "{{ groups }}"
#      run_once: yes
