####
#port 5082 ports.conf apache


- name: 'zainstaluj aplikacje apache2 i libapache2-mod-wsgi przekazując listę'
  apt: 
    pkg:
      - apache2
      - libapache2-mod-wsgi

- name: 'zainstaluj aplikacje apache2 i pozostale pakiety przy pomocy with_items'
  apt: 
    name: "{{ item }}"
  loop:
    - apache2
    - libapache2-mod-wsgi
      #- libapache2-mod-wsgi-py3 #dla python3
    - python-dev

- git:
    repo: https://github.com/sirkubax/naszaaplikacja.git
    dest: "{{ katalog_glowny }}"
    force: yes
  name: 'klonuj repozytorium aplikacji'

- pip: 
    requirements: "{{ katalog_aplikacji }}/requirements.txt"
    virtualenv: "{{ katalog_aplikacji }}/venv"
  name: 'zainicjalizuj virtualenv i zainstaluj zaleznosci' 
  notify:
    - restart apache

- name: 'wgraj definicje virtualhost naszaaplikacja.apache.conf{{ port }} jako template'
  template:
      src: naszaaplikacja.apache.conf
      dest: "/etc/apache2/sites-available/naszaaplikacja.apache{{ port }}.conf"
      backup: True
  notify:
    - restart apache

- name: 'usun /etc/apache2/sites-available/naszaaplikacja.apache jako template'
  file:
    path: "/etc/apache2/sites-available/naszaaplikacja.apache"
    state: absent
  notify:
    - restart apache

- name: 'konfiguruj apache do nasluchiwania na wybranym porcie'
  lineinfile: 
    dest: /etc/apache2/ports.conf
    line: "Listen {{ port }}"
    regexp: "^Listen {{ port }}"
  notify:
    - restart apache

- name: 'wylacz port 80'
  lineinfile: 
    dest: /etc/apache2/ports.conf
    regexp: "^Listen 80"
    state: absent
  notify:
    - restart apache

- name: 'wlacz virtualhost'
  shell: a2ensite {{ item }}
  args:
    creates: /etc/apache2/sites-enabled/{{ item }}
  loop: 
    - "naszaaplikacja.apache{{ port }}.conf"
  notify:
    - restart apache

- name: 'Wgraj sparametryzowany naszaaplikacja.wsgi (jako template)'
  template:
      src: naszaaplikacja.wsgi
      dest: "{{ katalog_aplikacji }}"
      backup: True
  notify:
    - restart apache

- name: 'Wgraj sparametryzowany config.cfg (jako template)'
  template:
      src: config.cfg
      dest: "{{ katalog_aplikacji }}"
      backup: True
  notify:
    - restart apache

- name: 'utworz katalog na logi'
  file:
    state: directory
    path: "{{ log_dir }}"
    owner: www-data
    group: www-data
    mode: 0755
  notify:
    - restart apache
