---
#Uruchomienie:
#~/szkolenie$ ansible-playbook playbooks/lab_a_test_hash_behaviour.yml
#
- hosts: localhost

  vars:
    nasz_slownik:
      x: 999
 

  tasks:
  - name: "Ustaw pierwszy fakt" 
    set_fact:
      nasz_slownik: 
        a: "{{ ansible_hostname }}"
  
  - name: "Wypisz pierwszy fakt" 
    debug: 
        msg: "{{ nasz_slownik }}"
  
  - name: "Ustaw drugi fakt - czy cos nadpisuje?" 
    set_fact:
      nasz_slownik: 
        b: 2
        c: 3
  
  - name: "Wypisz drugi fakt" 
    debug: msg="{{ nasz_slownik }}"

