---

- hosts: apache

  pre_tasks:
    - set_facts: 
        jakas_zmienna: 1234

  roles:
    - przykladowa_rola

  tasks:
    - name: "show time"
      shell: date

    - inclue_role:
        name: przykladowa_rola

  
    - name: Remove duplicate lines
      replace:
        path: /etc/apache2/ports.conf
        regexp: '^Listen 80$'
        replace: ''
      become: True
      inore_errors: true

