---
- hosts: apache

  vars:
      vars_files_var: ["vars/szkolenie.yml", "vars/szkolenie_vault.yml"]

  pre_tasks:
      - include_vars: "{{ item }}"
        with_items: "{{ vars_files_var }}"

  tasks:
    - name: "show time"
      shell: date

  #please examint the dictionary - output of known facts from sys_debug 

  roles:
    - sys_debug
    - { role: app_apache_template }

