---

- hosts: apache

  #     vars:
  #       sciezka_i_nazwa: ~/szkolenie_role_szkolenie12

  pre_tasks:
    - set_fact: 
        jakas_zmienna: 1234
      tags:
        - always

  roles:
    - przykladowa_rola

    - role: sys_init_common
      become: True

    - role: app_stworz_katalog
      vars:
        sciezka_i_nazwa: ~/szkolenie_role_szkolenie12

    - role: geerlingguy.apache
      become: True
     

#- hosts: mysql_group
#  
#  tasks: 
