---

- hosts: apache

  pre_tasks:
    - set_facts: 
        jakas_zmienna: 1234

  roles:
    - przykladowa_rola

  tasks:
    - name: "show time"
      shell: date

    - inclue_role:
        name: przykladowa_rola

  

