- hosts: naszaaplikacja_loadbalancer

  vars:
    katalog_glowny: /var/www/szkolenie
    katalog_aplikacji: "{{ katalog_glowny }}/aplikacja"

    #apache na wybranym porcie
    #lista_portow: [5081, 5082]


  become: true

  pre_tasks: []

  roles:
    - przykladowy_loadbalancer

