---
- hosts: apache
  gather_facts: True

- { hosts: mysql, gather_facts: False }
  
- hosts: mysql
  gather_facts: False

- hosts: all

  vars:
    zmiennaA: 1234

przyklad:
    cytryna: kwasna
    ala: nowa
    beza: swieza
    dzem: malinowy

  tasks:
    - ping:
      ignore_errors: True

    - when: true
      tags:
          - jakistag
      service: 
        state: restarted
        name: apache2
        enabled: True
        owner: ubuntu
      name: restart apache
      register: wynik_restartu

    - name: wypisz na ekran
      debug:
        msg: "{{ zmiennaA }}"


  roles:
    - sys_debug
    - { role: sys_init_common, become: True, tags: ['init_commom'] }
    - role: sys_manage_keys
      become: True
      register: mojazmienna

  handlers:
    - name: restart apache
      ping:

  #to jest komentarz
  gather_facts: smart
  become: True
  
  pre_tasks: []
  post_tasks: []

