---
- name: Create AWX Job Template
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    #awx_api_url: "https://your-awx-instance.com/api/v2/"
    #awx_api_token: "your-awx-api-token"
    #awx_api_url: "http://18.132.71.223:30080/api/v2/"
    awx_api_url: "http://35.181.6.117:30080/"
    awx_api_token: "yvggON53bh6kpT9Zji4AcPLnSmYZ5s"

  tasks:
    - name: Create Credential
      awx.awx.credential:
        name: "My Credential"
        description: "This is my AWX credential"
        credential_type: Machine
        inputs:
          username: "my-username"
          password: "my-password"
        state: "present"
        validate_certs: false
        controller_host: "{{ awx_api_url }}"
        controller_oauthtoken: "{{ awx_api_token }}"
        organization: ''
        user: admin

    - name: Create Project
      tower_project:
        name: "szkolenie09 - z - playbook"
        description: "This is my AWX project"
        scm_type: "git"
        scm_url: "https://github.com/sirkubax/for_awx.git"
        scm_branch: "main"
        #scm_credential: "Demo Credential"
        wait: true
        state: "present"
        #awx_host: "{{ awx_api_url }}"
        #awx_username: "admin"
        #awx_password: "4TNeHG5jnWc64CsK63CqHycDNgletUZ4"
        #awx_validate_certs: false
        validate_certs: false
        controller_host: "{{ awx_api_url }}"
        controller_oauthtoken: "{{ awx_api_token }}"
        organization: Default
      register: project

    - name: Create Job Template
      tower_job_template:
        name: "uruchom na maszynach awx jakis play"
        description: "This is my AWX Job Template"
        job_type: "run"
        inventory: "z_aws"
        project: "szkolenie09 - z - playbook"
        playbook: "playbooks/simple_playbook_szkolenie09.yml"
        credential: "klusz_ssh"
        #extra_vars: |
        #  my_var: "my_value"
        allow_simultaneous: true
        #limit: "my-host"
        #extra_data:
        #  webhook_credential: "My Webhook Credential"
        controller_host: "{{ awx_api_url }}"
        #controller_host: "http://18.132.71.223"
        controller_oauthtoken: "{{ awx_api_token }}"
        organization: Default
      delegate_to: localhost


# awx_host, awx_password, awx_username, awx_validate_certs. Supported parameters incl
#ude: credential (scm_credential), scm_branch, wait, scm_url, scm_track_submodules, controller_host (tower_host), scm_type, notification_templates_
#started, allow_override (scm_allow_override), validate_certs (tower_verify_ssl), controller_oauthtoken (tower_oauthtoken), local_path, controller_
#config_file (tower_config_file), controller_password (tower_password), scm_update_cache_timeout, update_project, interval, description, name, noti
#fication_templates_success, notification_templates_error, scm_clean, state, scm_delete_on_update, copy_from, scm_update_on_launch, controller_user
#name (tower_username), timeout (job_timeout), scm_refspec, custom_virtualenv, default_environment, organization
