IMAGE_NAME = "bento/ubuntu-20.04"
N = 2

Vagrant.configure("2") do |config|
    #config.ssh.insert_key = false
    id_rsa_pub = File.read("/home/kuba/workspace/bs/szkolenie/credentials/example_key.pub")
    config.vm.provision "copy ssh public key", type: "shell",
      inline: "echo \"#{id_rsa_pub}\" >> /home/vagrant/.ssh/authorized_keys"
    #config.ssh.insert_key = true
    #config.ssh.private_key_path = File.expand_path('/home/kuba/workspace/bs/szkolenie/credentials/example_key')
 

    config.vm.provider "virtualbox" do |v|
        v.memory = 768 
        v.cpus = 2
    end
      
    config.vm.define "ansible-master" do |master|
        master.vm.box = IMAGE_NAME
        master.vm.network "private_network", ip: "192.168.60.10"
        master.vm.hostname = "k8s-master"
        master.vm.provision "ansible" do |ansible|
            ansible.playbook = "master-playbook.yml"
            ansible.extra_vars = {
                node_ip: "192.168.60.10",
            }
            ansible.verbose = "-vvv"
        end
    end

    (1..N).each do |i|
        config.vm.define "node-#{i}" do |node|
            node.vm.box = IMAGE_NAME
            node.vm.network "private_network", ip: "192.168.60.#{i + 10}"
            node.vm.hostname = "node-#{i}"
            node.vm.provision "ansible" do |ansible|
                ansible.playbook = "node-playbook.yml"
                ansible.extra_vars = {
                    node_ip: "192.168.60.#{i + 10}",
                }
                ansible.verbose = "-vvv"
            end
        end
    end
end
